#!/bin/sh

. /etc/config/.env
. /etc/config/.cnf

echo '============= uci-default repositories =============='
# 24 使用 opkg 
# 25 使用 apk

if [ -x "$(command -v opkg)" ]; then
  PKG_MGR="opkg"
else
  PKG_MGR="apk"
fi

file_list="
/etc/opkg/distfeeds.conf
/etc/apk/repositories.d/distfeeds.list
"
for file in $file_list; do
  echo $file
  if [ -f "$file" ]; then
    cp "$file" "${file}.bak"
    sed -i 's_https\?://downloads.openwrt.org_https://mirrors.cernet.edu.cn/openwrt_' "$file"
    sed -i 's_https\?://downloads.immortalwrt.org_https://mirrors.cernet.edu.cn/immortalwrt_' "$file"
    sed -i 's_https\?://mirrors.vsean.net/openwrt_https://mirrors.cernet.edu.cn/immortalwrt_' "$file"
    cat $file
  fi
done

echo '============= uci-default base =============='
uci -q batch <<-EOF
  set system.@system[0].timezone="CST-8"
  set system.@system[0].zonename="Asia/Shanghai"

  delete system.ntp.server
  add_list system.ntp.server="ntp.tencent.com"
  add_list system.ntp.server="ntp1.aliyun.com"
  add_list system.ntp.server="ntp.ntsc.ac.cn"
  add_list system.ntp.server="cn.ntp.org.cn"

  commit system
EOF

echo '============= uci-default root =============='
if [ -n "$CNF_ROOT_PASSWD" ]; then
  (echo "$CNF_ROOT_PASSWD"; sleep 1; echo "$CNF_ROOT_PASSWD") | passwd > /dev/null
fi

echo '============= uci-default network =============='
# /etc/config/network
# uci show network
# 网卡信息
ifnames=""
for iface in /sys/class/net/*; do
  name=$(basename "$iface")
  if [ -e "$iface/device" ] && echo "$name" | grep -Eq '^eth|^en'; then
    count=$((count + 1))
    ifnames="$ifnames $name"
  fi
done
count=$(echo "$ifnames" | awk '{print NF}')
echo "count: $count"
echo "interfaces: $ifnames"

lan_ifname=""
wan_ifname=""
# 只有一个网卡 || 测试模式下，所有网卡作 lan 口
if [ "$count" -eq 1 ] || [ "$CNF_NET_MODE" = "test" ]; then
  lan_ifname=$ifnames
elif [ "$count" -gt 1 ]; then
  # 首个网卡作 wan 口
  wan_ifname=$(echo "$ifnames" | awk '{print $1}')
  # 其余网卡作 lan 口
  lan_ifname=$(echo "$ifnames" | awk '{for(i=2;i<=NF;i++) printf $i (i<NF?" ":"\n")}')
fi

# 创建 br-lan 网桥
while uci delete network.@device[0] >/dev/null 2>&1; do :; done
uci add network device
uci set network.@device[-1].name='br-lan'
uci set network.@device[-1].type='bridge'
for ifname in $lan_ifname; do
    uci add_list network.@device[-1].ports="$ifname"
done

uci -q delete network.lan
uci set network.lan="interface"
uci set network.lan.device="br-lan"
uci set network.lan.proto="$CNF_LAN_PROTO"
uci set network.lan.ipaddr="$CNF_LAN_IPADDR"
uci set network.lan.netmask="$CNF_LAN_NETMASK"
if [ "$CNF_NET_MODE" = "test" ]; then
  uci set network.lan.gateway="$CNF_LAN_GATEWAY"
  uci set network.lan.dns="$CNF_LAN_DNS"
  uci set dhcp.lan.ignore="1"
fi

uci -q delete network.wan
uci -q delete network.wan6
if [ -n "$wan_ifname" ]; then
  uci set network.wan="interface"
  uci set network.wan.device="$wan_ifname"
  uci set network.wan.proto="pppoe"
  uci set network.wan.username="$CNF_WAN_PPPOE_USERNAME"
  uci set network.wan.password="$CNF_WAN_PPPOE_PASSWORD"
fi

uci commit
