name: Build OpenWrt Firmware

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Config:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "step1"

  Docker:
    needs: [Config]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [immortalwrt, openwrt]
        target: [x86/64/generic]

    steps:
      - name: Generate Variables
        run: |
          export DEVICE_TARGET=$(echo ${{ matrix.target }} | awk -F '/' '{print $1}')
          echo "DEVICE_TARGET=$DEVICE_TARGET" >> $GITHUB_ENV
          export DEVICE_SUBTARGET=$(echo ${{ matrix.target }} | awk -F '/' '{print $2}')
          echo "DEVICE_SUBTARGET=$DEVICE_SUBTARGET" >> $GITHUB_ENV
          export DEVICE_PROFILE=$(echo ${{ matrix.target }} | awk -F '/' '{print $3}')
          echo "DEVICE_PROFILE=$DEVICE_PROFILE" >> $GITHUB_ENV

      - name: test
        run: |
          echo $GITHUB_ENV

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Prepare folders
        run: |
          mkdir -p ${{ github.workspace }}/bin

      - name: Make Image
        run: |
          docker run --rm \
            --user root \
            -v ${{ github.workspace }}/files:/openwrt/files \
            -v ${{ github.workspace }}/bin:/openwrt/bin \
            ${matrix.platform}/imagebuilder:${DEVICE_TARGET}-${DEVICE_SUBTARGET}-openwrt-24.10.2 \
            make image \
            PROFILE="${DEVICE_PROFILE}"
            BIN_DIR="/openwrt/bin" \
            FILES="/openwrt/files"

      # - name: List output
      #   run: |
      #     ls -la ${{ github.workspace }}/bin

      # - name: Upload firmware as artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: openwrt-output
      #     path: bin/**/*
      #     compression-level: 0

  DELRUNS:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 2
