name: Build OpenWrt Firmware

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # - platform: immortalwrt
          #   version: 24.10.2
          #   target: x86/64/generic
          - platform: openwrt
            version: 24.10.2
            target: x86/64/generic

    steps:
      - name: Generate Build Variables
        run: |
          TARGET=$(echo "${{ matrix.target }}" | cut -d'/' -f1)
          SUBTARGET=$(echo "${{ matrix.target }}" | cut -d'/' -f2)
          PROFILE=$(echo "${{ matrix.target }}" | cut -d'/' -f3)
      
          echo "TARGET=$TARGET" >> $GITHUB_ENV
          echo "SUBTARGET=$SUBTARGET" >> $GITHUB_ENV
          echo "PROFILE=$PROFILE" >> $GITHUB_ENV

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Build
        run: |
          ./scripts/build.sh

      # - name: Generate Build Variables
      #   shell: bash
      #   run: |
      #     TARGET=$(echo "${{ matrix.target }}" | cut -d'/' -f1)
      #     SUBTARGET=$(echo "${{ matrix.target }}" | cut -d'/' -f2)
      #     PROFILE=$(echo "${{ matrix.target }}" | cut -d'/' -f3)

      #     echo "TARGET=$TARGET" >> $GITHUB_ENV
      #     echo "SUBTARGET=$SUBTARGET" >> $GITHUB_ENV
      #     echo "PROFILE=$PROFILE" >> $GITHUB_ENV

      #     PACKAGES=$(cat $GITHUB_WORKSPACE/config/packages.config | tr -s "\n" " ")
      #     echo "PACKAGES=$PACKAGES" >> $GITHUB_ENV

      # - name: Prepare Output Directory
      #   run: mkdir -p bin

      # - name: Build OpenWrt Firmware via Docker
      #   env:
      #     PLATFORM: ${{ matrix.platform }}
      #     VERSION: ${{ matrix.version }}
      #     TARGET: ${{ env.TARGET }}
      #     SUBTARGET: ${{ env.SUBTARGET }}
      #     PROFILE: ${{ env.PROFILE }}
      #     PACKAGES: ${{env.PACKAGES}}
      #   run: |
      #     if [ "$PLATFORM" = "openwrt" ]; then
      #       IMAGE_TAG="${TARGET}-${SUBTARGET}-${VERSION}"
      #     else
      #       IMAGE_TAG="${TARGET}-${SUBTARGET}-openwrt-${VERSION}"
      #     fi

      #     echo "Using Docker image: ${PLATFORM}/imagebuilder:${IMAGE_TAG}"

      #     cat <<EOF > docker.env
      #       PLATFORM=${PLATFORM}
      #       VERSION=${VERSION}
      #       TARGET=${TARGET}
      #       SUBTARGET=${SUBTARGET}
      #       PROFILE=${PROFILE}
      #       PACKAGES=${PACKAGES}
      #       IMAGE_TAG=${IMAGE_TAG}
      #     EOF

      #     docker run --rm \
      #       --user root \
      #       --env-file docker.env \
      #       -v ${{ github.workspace }}/files:/openwrt/files \
      #       -v ${{ github.workspace }}/bin:/openwrt/bin \
      #       -v ${{ github.workspace }}/scripts:/openwrt/scripts \
      #       ${PLATFORM}/imagebuilder:${IMAGE_TAG} \
      #       /bin/bash /openwrt/scripts/build.sh

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        env:
          TARGET: ${{ env.TARGET }}
          SUBTARGET: ${{ env.SUBTARGET }}
        with:
          name: ${{ matrix.platform }}-${{ env.TARGET }}-${{ env.SUBTARGET }}-${{ matrix.version }}
          path: bin/

      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          TARGET: ${{ env.TARGET }}
          SUBTARGET: ${{ env.SUBTARGET }}
        with:
          overwrite_files: true
          tag_name: ${{ matrix.platform }}-${{ env.TARGET }}-${{ env.SUBTARGET }}-${{ matrix.version }}
          body_path: bin/info.md
          files: bin/*
